fail_fast: false
default_install_hook_types: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: sh -c 'yarn test:format'
        language: system
        files: \.(ts)$
        stages: [commit]
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: sh -c 'yarn test:lint'
        language: system
        files: \.(ts)$
        stages: [commit]
  - repo: local
    hooks:
      - id: test api
        name: test api
        entry: sh -c 'yarn test'
        language: system
        files: \.(ts)$
        stages: [commit]
